// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_X8g_xO7y4Mw7x5qNuxc4HVIX4jtspaY',
    appId: '1:200221143824:web:70c65d4275410948ac2b95',
    messagingSenderId: '200221143824',
    projectId: 'prototype-a5cb9',
    authDomain: 'prototype-a5cb9.firebaseapp.com',
    storageBucket: 'prototype-a5cb9.appspot.com',
    measurementId: 'G-5K4JEE6EH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_fX664blI2gC-bcHwALBH27cNbE6gqHA',
    appId: '1:200221143824:android:129e0b0a9d35086fac2b95',
    messagingSenderId: '200221143824',
    projectId: 'prototype-a5cb9',
    storageBucket: 'prototype-a5cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6X8epq3CIlhuJc4TTIusbSVEehuU5Hfo',
    appId: '1:200221143824:ios:8793bd27ba2026a5ac2b95',
    messagingSenderId: '200221143824',
    projectId: 'prototype-a5cb9',
    storageBucket: 'prototype-a5cb9.appspot.com',
    iosClientId: '200221143824-4bmkd7jrpk5fir735u3i75q0qfh4mu47.apps.googleusercontent.com',
    iosBundleId: 'com.example.prototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6X8epq3CIlhuJc4TTIusbSVEehuU5Hfo',
    appId: '1:200221143824:ios:8793bd27ba2026a5ac2b95',
    messagingSenderId: '200221143824',
    projectId: 'prototype-a5cb9',
    storageBucket: 'prototype-a5cb9.appspot.com',
    iosClientId: '200221143824-4bmkd7jrpk5fir735u3i75q0qfh4mu47.apps.googleusercontent.com',
    iosBundleId: 'com.example.prototype',
  );
}
